# -*- coding: utf-8 -*-
"""FoodBalanceSheet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycHI5NnGAHxICLX4-3m22hc3yEfnS23u

# Food Balance Sheet Analysis

## Reading Data
"""

# importing the libraries that will be used
import pandas as pd
import numpy as np

# Reading the data from the dataset
food_df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin-1")

"""## Checking the data"""

# previewing the first 5 records of the dataset
food_df.head()

# checking the number of rows and columns
food_df.shape

"""Question 3: What is the total number and percentage of missing data in 2014 to 3 decomal places"""

# missing data in 2014
food_df['Y2014'].isnull().sum()

# percentage of missing data in 2014 in 3 desimal places
round((food_df['Y2014'].isnull().sum()/food_df.shape[0])*100,3)

"""Question 5: Select columns 'Y2017' and 'Area', Perform a groupby operation on 'Area'. Which of these Areas had the lowest sum in 2017?"""

# lowest 7th sum in 2017
food_df.groupby("Area")["Y2017"].sum().sort_values(ascending=False)

"""Question 8: What is the total sum of Wine produced in 2015 and 2018 respectively?"""

# total sum of wine production in 2015
food_df.groupby(food_df["Item"] == "Wine")["Y2015"].sum()

# total sum of wine production in 2018
food_df.groupby(food_df["Item"] == "Wine")["Y2018"].sum()

"""Question 9: Perform a groupby operation on 'Element'. What year has the highest sum of Stock Variation?"""

# year with the highest sum of stock Variation as per Element
food_df.groupby(food_df["Element"] == "Stock Variation")["Y2014","Y2015","Y2016","Y2017","Y2018"].sum()

"""Question 10: Perform a groupby operation on 'Element'. What is the total number of the sum of Processing in 2017?"""

# total number of the sum of processing in 2017
food_df.groupby(food_df["Element"] == "Processing")["Y2017"].sum()

"""Question 12: What is the mean and standard deviation across the whole dataset for the year 2017 to 2 decimal places?"""

# mean and standard deviation across the whole dataset for the year 2017 in 2 decimal places
round(food_df['Y2017'].describe(),2)

"""Question 16: Select columns 'Y2017' and 'Area', perform a groupby operation on 'Area'. Which Area had the highest sum in 2017?"""

# areas with the highest sum in 2017
food_df['Y2017'].groupby(food_df['Area']).sum().sort_values(ascending=False)

"""Question 17: What is the total number of unique countries in the dataset?"""

food_df['Area'].nunique()

"""Question 19: What is the total Protein supply quantity in Madagascar in 2015?"""

madagascar_df = food_df.query('Area == "Madagascar"')
madagascar_df

madagascar_df['Y2015'].groupby(madagascar_df['Element'] == 'Protein supply quantity (g/capita/day)').sum()

"""Question 20: Which year had the least correlarion with 'Element Code'?"""

# the year with the least correlation with 'Element Code'
food_df.corr()